syscalls = '/usr/include/x86_64-linux-gnu/asm/unistd_64.h'

list = []
for line in open(syscalls):
	if '__NR_' in line:
		t, name, number = line.split()
		name = name.replace('__NR_', '')
		number = int(number)
		list.append((name, number))


print '// Automatically generated by table_gen.py for %s' % syscalls
print 'const char *syscall_to_name[] = {'

prev_syscall = -1
for i in list:
	# Check that there are no holes.
	if prev_syscall + 1 != i[1]:
		for j in xrange(prev_syscall+1, i[1]):
			print '  "%s", // %d' % ("unknown_%d" % j, j)

	prev_syscall = i[1]
	print '  "%s", // %d' % (i[0], i[1])

print '};'